name: Build Azure Automation Repo

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: RunBuildScript
        shell: pwsh
        run: |
          ./AutomatedControls/Build.ps1
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AutomatedControls
          path: AutomatedControls