name: Deploy Azure Automation

on:
    workflow_call:
      inputs:
        environment:
          description: 'The environment to deploy to'
          required: true
          type: string
      secrets:
        CLIENT_ID:
          description: 'The client id of the service principal used to deploy'
          required: true
        AZUREAUTOMATIONSPNPW:
          description: 'The password of the service principal used to deploy'
          required: true
        SUBSCRIPTION_ID:
          description: 'The subscription id to deploy to'
          required: true
        TENANT_ID:
          description: 'The tenant id to deploy to'
          required: true
jobs:
    deploy:
        environment: ${{ inputs.environment }}
        runs-on: windows-latest
        steps:
          - name: Download artifact
            uses: actions/download-artifact@v3
            with:
              name: AutomatedControls
              path: ./
          - name: Azure Login
            uses: Azure/login@v1.4.6
            with:
              creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.AZUREAUTOMATIONSPNPW }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
              enable-AzPSSession: true 
          - name: Run deploy script
            shell: pwsh
            run: |
              ./Deploy.ps1 -AutomationAccountName "${{vars.AutomationAccountName}}" -ResourceGroupName "${{vars.ResourceGroupName}}" 