name: Build and Deploy to Azure Automation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch  name'
        required: true
        default: 'main'
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy-dev:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: DEV
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      AZUREAUTOMATIONSPNPW: ${{ secrets.AZUREAUTOMATIONSPNPW }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  deploy-prod:
    needs: deploy-dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: PROD
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      AZUREAUTOMATIONSPNPW: ${{ secrets.AZUREAUTOMATIONSPNPW }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}