name: Deploy to Azure Automation

on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.AZUREAUTOMATIONSPNPW }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true 
      - name: RunDeployScript
        shell: pwsh
        run: |
          .\AutomatedControls\DeployToAzureAutomation.ps1
