name: Build and Deploy to Azure Automation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch  name'
        required: true
        default: 'main'
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy-dev:
    runs-on: windows-latest
    environment: DEV
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Deploy to Dev
        uses: ./.github/workflows/deploy.yml
  deploy-prod:
    needs: deploy-dev
    runs-on: windows-latest
    environment: PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Deploy to Dev
        uses: ./.github/workflows/deploy.yml
